### ISSUE TITLE
concurrent use of MeasureString causes panic

### ISSUE THREAD

**Issue by psanford** [fogleman/gg#23]
The following program panics consistently for me:

```
package main

import (
	"fmt"
	"strconv"
	"sync"

	"golang.org/x/image/font"

	"github.com/fogleman/gg"
)

var face font.Face

func main() {
	f, err := gg.LoadFontFace("/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf", 12)
	if err != nil {
		panic(err)
	}
	face = f

	var wg sync.WaitGroup

	for i := 0; i < 100; i++ {
		wg.Add(1)
		go func() {
			drawIt(i)
			wg.Done()
		}()
	}

	wg.Wait()
}

func drawIt(id int) {
	for i := 0; i < 100; i++ {
		gctx := gg.NewContext(1000, 1000)
		gctx.SetFontFace(face)

		w, h := gctx.MeasureString(strconv.Itoa(i))
		fmt.Printf("%02d %d %f %f\n", id, i, w, h)
	}
}
```

The panic is: 
```
panic: runtime error: index out of range

goroutine 58 [running]:
vendor/github.com/golang/freetype/truetype.(*GlyphBuf).load(0xc42009eb00, 0x1001600000000, 0xc400000033, 0x16)
        /home/psanford/projects/nearbuy/storenet/go/src/vendor/github.com/golang/freetype/truetype/glyph.go:231 +0x70e
vendor/github.com/golang/freetype/truetype.(*GlyphBuf).Load(0xc42009eb00, 0xc4200103c0, 0x1600000300, 0x0, 0x40bdc8, 0x4ea420)
        /home/psanford/projects/nearbuy/storenet/go/src/vendor/github.com/golang/freetype/truetype/glyph.go:102 +0xd2
vendor/github.com/golang/freetype/truetype.(*face).GlyphAdvance(0xc42009c000, 0x33, 0x0)
        /home/psanford/projects/nearbuy/storenet/go/src/vendor/github.com/golang/freetype/truetype/face.go:345 +0x6e
vendor/golang.org/x/image/font.MeasureString(0x579a80, 0xc42009c000, 0xc4236b8122, 0x1, 0x3)
        /home/psanford/projects/nearbuy/storenet/go/src/vendor/golang.org/x/image/font/font.go:287 +0x84
vendor/golang.org/x/image/font.(*Drawer).MeasureString(0xc420c96eb0, 0xc4236b8122, 0x1, 0xc4236b8122)
        /home/psanford/projects/nearbuy/storenet/go/src/vendor/golang.org/x/image/font/font.go:201 +0x4c
vendor/github.com/fogleman/gg.(*Context).MeasureString(0xc420058500, 0xc4236b8122, 0x1, 0x4, 0x4)
        /home/psanford/projects/nearbuy/storenet/go/src/vendor/github.com/fogleman/gg/context.go:696 +0x88
main.drawIt(0x64)
        /home/psanford/projects/nearbuy/storenet/go/src/pms/fontsafe/main.go:47 +0xb1
main.main.func1(0xc42000e3e0, 0xc42000e3d0)
        /home/psanford/projects/nearbuy/storenet/go/src/pms/fontsafe/main.go:34 +0x2e
created by main.main
        /home/psanford/projects/nearbuy/storenet/go/src/pms/fontsafe/main.go:36 +0x108
exit status 2
```

According to https://godoc.org/golang.org/x/image/font#Face "A Face is not safe for concurrent use by multiple goroutines, as its methods may re-use implementation-specific caches and mask image buffers."

At the very least it seems like the package level LoadFontFace should say that it is not safe for concurrent use.

**Comment by justinclift** [comment]
Gah.  This is what I'm hitting too, converting an image sequence generator to use [goroutines](https://github.com/justinclift/matrixMultDrawTest). :frowning: 

So far, the code only functions - eg without panicing - if I strip out all calls to `MeasureString()` and `DrawString*()`, as the `DrawString()` functions also call `MeasureString()` internally.

Any idea of a workaround?  Leaving things to run single-threaded isn't really an option.

Guessing all the text will have to be moved out of the generated frames permanently though. :frowning:

**Comment by psanford** [comment]
We worked around this by using the Context.LoadFontFace() method instead of the package level method.

**Comment by justinclift** [comment]
Thanks @psanford, I'll give that a go. :smile:

**Comment by justinclift** [comment]
Yep, that works.  Awesome stuff @psanford, thank you. :smile:

**Comment by justinclift** [comment]
As a possibly useful data point, another way to work around it is by moving the same `gg.LoadFontFace()` calls inside the goroutines.

It makes sense upon thinking about it, as both approaches are ensuring each goroutine get's it's own font face to work with.  So no collision problems.
